version: "2.0"
services:
  phpmyadmin:
    container_name: phpmyadmin_container
    image: mjtech009/phpmyadmin_multi_host
    restart: on-failure
    env_file: rds.env
    ports:
      - '0.0.0.0:81:80'
